export async function deleteMeal() {
  try {
    console.log("\n\n[deleteMeal] Running...");
  } catch (e) {
    console.error("\n\n[deleteMeal] Error: ", e);
  }
}
